# Generated by Django 5.1.1 on 2024-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticad', '0004_userextended_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='nickname',
        ),
        migrations.AddField(
            model_name='userextended',
            name='me_conhece_como',
            field=models.TextField(blank=True, null=True),
        ),
    ]
